let perfumes = [
  {
    name: "Leather Rosa",
    finder: "LEATHERROSA",
    brand: "Angela Flanders",
    type: "Eau de Parfum",
    size: "50ml and Sample",
    scent: "Floral and Woody",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Taffeta",
    finder: "TAFFETA",
    brand: "Angela Flanders",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Floral and Green",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Lawn",
    finder: "LAWN",
    brand: "Angela Flanders",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Green and Fresh",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Halfeti",
    finder: "HALFETI",
    brand: "Penhaligon's",
    type: "Eau de Parfum",
    size: "100ml and Miniature",
    scent: "Woody and Spicy",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Elisabethan Rose",
    finder: "ELISABETHANROSE",
    brand: "Penhaligon's",
    type: "Eau de Parfum",
    size: "Miniature",
    scent: "Floral and Woody",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Luna",
    finder: "LUNA",
    brand: "Penhaligon's",
    type: "Eau de Toilette",
    size: "Miniature",
    scent: "Floral and Fresh",
    longevity: "2 to 3 hours",
    impression: "Not recorded.",
  },
  {
    name: "The Favourite",
    finder: "THEFAVOURITE",
    brand: "Penhaligon's",
    type: "Eau de Parfum",
    size: "Miniature",
    scent: "Floral and Woody",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Empressa",
    finder: "EMPRESSA",
    brand: "Penhaligon's",
    type: "Eau de Parfum",
    size: "Miniature and Sample",
    scent: "Floral and Spicy",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "J'adore",
    finder: "JADORE",
    brand: "Dior",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Floral and Fruity",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Gaultier Divine",
    finder: "GAULTIERDIVINE",
    brand: "Jean Paul Gaultier",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Floral and Aquatic",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Classique",
    finder: "CLASSIQUE",
    brand: "Jean Paul Gaultier",
    type: "Eau de Toilette",
    size: "Sample",
    scent: "Floral and Gourmand",
    longevity: "2 to 3 hours",
    impression: "Not recorded.",
  },
  {
    name: "Activist",
    finder: "ACTIVIST",
    brand: "The Body Shop",
    type: "Eau de Toilette",
    size: "100ml",
    scent: "Woody and Spicy",
    longevity: "2 to 3 hours",
    impression: "Not recorded.",
  },
  {
    name: "Brown No. 85",
    finder: "BROWNNO85",
    brand: "Next",
    type: "Eau de Toilette",
    size: "30ml",
    scent: "Spicy and Aquatic",
    longevity: "2 to 3 hours",
    impression: "Not recorded.",
  },
  {
    name: "186",
    finder: "186",
    brand: "The Essence Vault",
    type: "Eau de Parfum",
    size: "30ml",
    scent: "Spicy and Fresh",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Prada Paradoxe",
    finder: "PRADAPARADOXE",
    brand: "Prada",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Floral and Gourmand",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Prada Paradoxe Intense",
    finder: "PRADAPARADOXEINTENSE",
    brand: "Prada",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Floral and Spicy",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Black Opium",
    finder: "BLACKOPIUM",
    brand: "Yves Saint Laurent",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Gourmand and Spicy",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "MYSLF",
    finder: "MYSLF",
    brand: "Yves Saint Laurent",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Woody and Fresh",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "The Ghost in the Shell",
    finder: "THEGHOSTINTHESHELL",
    brand: "Etat Libre d'Orange",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Fresh and Floral",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Fat Electrician",
    finder: "FATELECTRICIAN",
    brand: "Etat Libre d'Orange",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Spicy and Woody",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "She Was An Anomaly",
    finder: "SHEWASANANOMALY",
    brand: "Etat Libre d'Orange",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Floral and Woody",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Hermann A Mes Cotes Me Paraissait Une Ombre",
    finder: "HERMANNAMESCOTESMEPARAISSAITUNEOMBRE",
    brand: "Etat Libre d'Orange",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Spicy and Chypre",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Les Fleurs Du Dechet – I Am Trash",
    finder: "LESFLEURSDUDECHET–IAMTRASH",
    brand: "Etat Libre d'Orange",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Floral and Fruity",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Like This",
    finder: "LIKETHIS",
    brand: "Etat Libre d'Orange",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Floral and Spicy",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "You Or Someone Like You",
    finder: "YOUORSOMEONELIKEYOU",
    brand: "Etat Libre d'Orange",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Fresh and Green",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Soul of My Soul",
    finder: "SOULOFMYSOUL",
    brand: "Etat Libre d'Orange",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Spicy and Fresh",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Eau de Protection",
    finder: "EAUDEPROTECTION",
    brand: "Etat Libre d'Orange",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Floral and Spicy",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Divin' Enfant",
    finder: "DIVINENFANT",
    brand: "Etat Libre d'Orange",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Floral and Fruity",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Book",
    finder: "BOOK",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Woody and Fresh",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Gold",
    finder: "GOLD",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Woody and Gourmand",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Velvet",
    finder: "VELVET",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Amber and Gourmand",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Moss",
    finder: "MOSS",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Chypre and Spicy",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Paper",
    finder: "PAPER",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Woody and Amber",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Milk",
    finder: "MILK",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Gourmand and Amber",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Book-",
    finder: "BOOK-",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Fresh and Woody",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Gold-",
    finder: "GOLD-",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Gourmand and Woody",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Velvet-",
    finder: "VELVET-",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Amber and Floral",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Moss-",
    finder: "MOSS-",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Amber and Green",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Paper-",
    finder: "PAPER-",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Fresh and Amber",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Milk-",
    finder: "MILK-",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Amber and Fresh",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Book+",
    finder: "BOOK+",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Smoky and Green",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Gold+",
    finder: "GOLD+",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Gourmand and Spicy",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Velvet+",
    finder: "VELVET+",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Amber and Spicy",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Moss+",
    finder: "MOSS+",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Chypre and Amber",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Paper+",
    finder: "PAPER+",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Woody and Green",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "Milk+",
    finder: "MILK+",
    brand: "Commodity Fragrances",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Gourmand and Smoky",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "AlUla",
    finder: "ALULA",
    brand: "Penhaligon's",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Amber and Smoky",
    longevity: "4 to 5 hours",
    impression: "Not recorded.",
  },
  {
    name: "No. 5",
    finder: "NO5",
    brand: "Chanel",
    type: "Eau de Parfum",
    size: "35ml",
    scent: "Aldehyde and Floral",
    longevity: "4 to 5 hours",
    impression:
      "Aldehyde forward, champagne bubble nose tickle, expensive, clean, powdery, floral with a hint of spice in the middle.",
  },
  {
    name: "Gabrielle Essence",
    finder: "GABRIELLEESSENCE",
    brand: "Chanel",
    type: "Eau de Parfum",
    size: "Sample",
    scent: "Floral and Fruity",
    longevity: "4 to 5 hours",
    impression:
      "Fruit warmed floral, fruits range from citruses to jammy, musk base.",
  },
  {
    name: "Bleu de Chanel",
    finder: "BLEUDECHANEL",
    brand: "Chanel",
    type: "Parfum",
    size: "Sample",
    scent: "Fresh and Woody",
    longevity: "8 hours",
    impression:
      "Aromatic, minty, reminds me of Davidoff's Cool Water, slight spice in middle notes.",
  },
  {
    name: "Le Male",
    finder: "LEMALE",
    brand: "Jean Paul Gaultier",
    type: "Eau de Toilette",
    size: "Sample",
    scent: "Fresh and Gourmand",
    longevity: "2 to 3 hours",
    impression:
      "Summery, floral dessert, too sweet to be an Amber, fresh especially in the top notes, also Lavender, Mint and Orange Blossom.",
  },
];
